2022-07-27 15:49:09,493 INFO    MainThread:3333978 [internal.py:wandb_internal():90] W&B internal server running at pid: 3333978, started at: 2022-07-27 15:49:09.490001
2022-07-27 15:49:09,517 INFO    WriterThread:3333978 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220727_154906-25cz5umo/run-25cz5umo.wandb
2022-07-27 15:49:09,518 DEBUG   HandlerThread:3333978 [handler.py:handle_request():141] handle_request: run_start
2022-07-27 15:49:09,558 DEBUG   HandlerThread:3333978 [meta.py:__init__():35] meta init
2022-07-27 15:49:09,558 DEBUG   HandlerThread:3333978 [meta.py:__init__():49] meta init done
2022-07-27 15:49:09,559 DEBUG   HandlerThread:3333978 [meta.py:probe():209] probe
2022-07-27 15:49:09,578 DEBUG   HandlerThread:3333978 [meta.py:_setup_git():199] setup git
2022-07-27 15:49:09,699 DEBUG   HandlerThread:3333978 [meta.py:_setup_git():206] setup git done
2022-07-27 15:49:09,699 DEBUG   HandlerThread:3333978 [meta.py:_save_pip():53] save pip
2022-07-27 15:49:09,702 DEBUG   HandlerThread:3333978 [meta.py:_save_pip():67] save pip done
2022-07-27 15:49:09,704 DEBUG   HandlerThread:3333978 [meta.py:_save_conda():74] save conda
2022-07-27 15:49:18,525 WARNING MainThread:3333978 [internal.py:is_dead():387] Internal process exiting, parent pid 3281441 disappeared
2022-07-27 15:49:18,525 ERROR   MainThread:3333978 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-27 15:49:18,526 INFO    SenderThread:3333978 [sender.py:finish():1111] shutting down sender
2022-07-27 15:49:18,526 INFO    WriterThread:3333978 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220727_154906-25cz5umo/run-25cz5umo.wandb
2022-07-27 15:49:20,547 DEBUG   HandlerThread:3333978 [meta.py:_save_conda():84] save conda done
2022-07-27 15:49:20,547 DEBUG   HandlerThread:3333978 [meta.py:probe():247] probe done
2022-07-27 15:49:21,326 INFO    HandlerThread:3333978 [handler.py:finish():806] shutting down handler
2022-07-27 15:49:21,326 INFO    MainThread:3333978 [internal.py:handle_exit():80] Internal process exited
