2022-08-24 21:51:40,458 INFO    MainThread:1558323 [internal.py:wandb_internal():90] W&B internal server running at pid: 1558323, started at: 2022-08-24 21:51:40.455765
2022-08-24 21:51:40,461 INFO    WriterThread:1558323 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220824_215136-3tbtxnr2/run-3tbtxnr2.wandb
2022-08-24 21:51:40,462 DEBUG   HandlerThread:1558323 [handler.py:handle_request():141] handle_request: run_start
2022-08-24 21:51:40,472 DEBUG   HandlerThread:1558323 [meta.py:__init__():35] meta init
2022-08-24 21:51:40,473 DEBUG   HandlerThread:1558323 [meta.py:__init__():49] meta init done
2022-08-24 21:51:40,473 DEBUG   HandlerThread:1558323 [meta.py:probe():209] probe
2022-08-24 21:51:40,481 DEBUG   HandlerThread:1558323 [meta.py:_setup_git():199] setup git
2022-08-24 21:51:40,566 DEBUG   HandlerThread:1558323 [meta.py:_setup_git():206] setup git done
2022-08-24 21:51:40,566 DEBUG   HandlerThread:1558323 [meta.py:_save_pip():53] save pip
2022-08-24 21:51:40,572 DEBUG   HandlerThread:1558323 [meta.py:_save_pip():67] save pip done
2022-08-24 21:51:40,573 DEBUG   HandlerThread:1558323 [meta.py:_save_conda():74] save conda
2022-08-24 21:51:49,471 WARNING MainThread:1558323 [internal.py:is_dead():387] Internal process exiting, parent pid 1558084 disappeared
2022-08-24 21:51:49,471 ERROR   MainThread:1558323 [internal.py:wandb_internal():149] Internal process shutdown.
2022-08-24 21:51:49,472 INFO    SenderThread:1558323 [sender.py:finish():1111] shutting down sender
2022-08-24 21:51:50,466 INFO    WriterThread:1558323 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220824_215136-3tbtxnr2/run-3tbtxnr2.wandb
2022-08-24 21:51:52,072 DEBUG   HandlerThread:1558323 [meta.py:_save_conda():84] save conda done
2022-08-24 21:51:52,072 DEBUG   HandlerThread:1558323 [meta.py:probe():247] probe done
2022-08-24 21:51:52,668 INFO    HandlerThread:1558323 [handler.py:finish():806] shutting down handler
2022-08-24 21:51:52,669 INFO    MainThread:1558323 [internal.py:handle_exit():80] Internal process exited
