2022-11-10 09:45:55,578 INFO    MainThread:2309778 [internal.py:wandb_internal():90] W&B internal server running at pid: 2309778, started at: 2022-11-10 09:45:55.576079
2022-11-10 09:45:55,616 INFO    WriterThread:2309778 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221110_094553-3b33cevn/run-3b33cevn.wandb
2022-11-10 09:45:55,616 DEBUG   HandlerThread:2309778 [handler.py:handle_request():141] handle_request: run_start
2022-11-10 09:45:55,639 DEBUG   HandlerThread:2309778 [meta.py:__init__():35] meta init
2022-11-10 09:45:55,640 DEBUG   HandlerThread:2309778 [meta.py:__init__():49] meta init done
2022-11-10 09:45:55,640 DEBUG   HandlerThread:2309778 [meta.py:probe():209] probe
2022-11-10 09:45:55,660 DEBUG   HandlerThread:2309778 [meta.py:_setup_git():199] setup git
2022-11-10 09:45:55,780 DEBUG   HandlerThread:2309778 [meta.py:_setup_git():206] setup git done
2022-11-10 09:45:55,780 DEBUG   HandlerThread:2309778 [meta.py:_save_pip():53] save pip
2022-11-10 09:45:55,783 DEBUG   HandlerThread:2309778 [meta.py:_save_pip():67] save pip done
2022-11-10 09:45:55,785 DEBUG   HandlerThread:2309778 [meta.py:_save_conda():74] save conda
2022-11-10 09:46:13,904 DEBUG   HandlerThread:2309778 [meta.py:_save_conda():84] save conda done
2022-11-10 09:46:13,904 DEBUG   HandlerThread:2309778 [meta.py:probe():247] probe done
2022-11-10 09:46:36,644 WARNING MainThread:2309778 [internal.py:is_dead():387] Internal process exiting, parent pid 2309709 disappeared
2022-11-10 09:46:36,644 ERROR   MainThread:2309778 [internal.py:wandb_internal():149] Internal process shutdown.
2022-11-10 09:46:37,307 INFO    HandlerThread:2309778 [handler.py:finish():806] shutting down handler
2022-11-10 09:46:37,307 INFO    WriterThread:2309778 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221110_094553-3b33cevn/run-3b33cevn.wandb
2022-11-10 09:46:37,611 INFO    SenderThread:2309778 [sender.py:finish():1111] shutting down sender
2022-11-10 09:46:37,611 INFO    MainThread:2309778 [internal.py:handle_exit():80] Internal process exited
