2022-07-23 20:01:25,024 INFO    MainThread:1421704 [internal.py:wandb_internal():90] W&B internal server running at pid: 1421704, started at: 2022-07-23 20:01:25.021298
2022-07-23 20:01:25,026 INFO    WriterThread:1421704 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220723_200122-1zmrwpde/run-1zmrwpde.wandb
2022-07-23 20:01:25,026 DEBUG   HandlerThread:1421704 [handler.py:handle_request():141] handle_request: run_start
2022-07-23 20:01:25,036 DEBUG   HandlerThread:1421704 [meta.py:__init__():35] meta init
2022-07-23 20:01:25,036 DEBUG   HandlerThread:1421704 [meta.py:__init__():49] meta init done
2022-07-23 20:01:25,036 DEBUG   HandlerThread:1421704 [meta.py:probe():209] probe
2022-07-23 20:01:25,049 DEBUG   HandlerThread:1421704 [meta.py:_setup_git():199] setup git
2022-07-23 20:01:25,129 DEBUG   HandlerThread:1421704 [meta.py:_setup_git():206] setup git done
2022-07-23 20:01:25,129 DEBUG   HandlerThread:1421704 [meta.py:_save_pip():53] save pip
2022-07-23 20:01:25,133 DEBUG   HandlerThread:1421704 [meta.py:_save_pip():67] save pip done
2022-07-23 20:01:25,133 DEBUG   HandlerThread:1421704 [meta.py:_save_conda():74] save conda
2022-07-23 20:01:33,923 DEBUG   HandlerThread:1421704 [meta.py:_save_conda():84] save conda done
2022-07-23 20:01:33,923 DEBUG   HandlerThread:1421704 [meta.py:probe():247] probe done
2022-07-23 20:01:34,033 WARNING MainThread:1421704 [internal.py:is_dead():387] Internal process exiting, parent pid 1403537 disappeared
2022-07-23 20:01:34,033 ERROR   MainThread:1421704 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-23 20:01:34,036 INFO    SenderThread:1421704 [sender.py:finish():1111] shutting down sender
2022-07-23 20:01:34,485 INFO    HandlerThread:1421704 [handler.py:finish():806] shutting down handler
2022-07-23 20:01:35,029 INFO    WriterThread:1421704 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220723_200122-1zmrwpde/run-1zmrwpde.wandb
2022-07-23 20:01:35,031 INFO    MainThread:1421704 [internal.py:handle_exit():80] Internal process exited
