2022-11-10 09:48:22,952 INFO    MainThread:2310991 [internal.py:wandb_internal():90] W&B internal server running at pid: 2310991, started at: 2022-11-10 09:48:22.950030
2022-11-10 09:48:22,976 INFO    WriterThread:2310991 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221110_094820-19v4t6aw/run-19v4t6aw.wandb
2022-11-10 09:48:22,977 DEBUG   HandlerThread:2310991 [handler.py:handle_request():141] handle_request: run_start
2022-11-10 09:48:23,010 DEBUG   HandlerThread:2310991 [meta.py:__init__():35] meta init
2022-11-10 09:48:23,010 DEBUG   HandlerThread:2310991 [meta.py:__init__():49] meta init done
2022-11-10 09:48:23,010 DEBUG   HandlerThread:2310991 [meta.py:probe():209] probe
2022-11-10 09:48:23,028 DEBUG   HandlerThread:2310991 [meta.py:_setup_git():199] setup git
2022-11-10 09:48:23,148 DEBUG   HandlerThread:2310991 [meta.py:_setup_git():206] setup git done
2022-11-10 09:48:23,148 DEBUG   HandlerThread:2310991 [meta.py:_save_pip():53] save pip
2022-11-10 09:48:23,159 DEBUG   HandlerThread:2310991 [meta.py:_save_pip():67] save pip done
2022-11-10 09:48:23,160 DEBUG   HandlerThread:2310991 [meta.py:_save_conda():74] save conda
2022-11-10 09:48:41,370 DEBUG   HandlerThread:2310991 [meta.py:_save_conda():84] save conda done
2022-11-10 09:48:41,370 DEBUG   HandlerThread:2310991 [meta.py:probe():247] probe done
2022-11-10 09:49:04,010 WARNING MainThread:2310991 [internal.py:is_dead():387] Internal process exiting, parent pid 2310921 disappeared
2022-11-10 09:49:04,010 ERROR   MainThread:2310991 [internal.py:wandb_internal():149] Internal process shutdown.
2022-11-10 09:49:04,578 INFO    HandlerThread:2310991 [handler.py:finish():806] shutting down handler
2022-11-10 09:49:04,578 INFO    WriterThread:2310991 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221110_094820-19v4t6aw/run-19v4t6aw.wandb
2022-11-10 09:49:05,003 INFO    SenderThread:2310991 [sender.py:finish():1111] shutting down sender
2022-11-10 09:49:05,004 INFO    MainThread:2310991 [internal.py:handle_exit():80] Internal process exited
