2022-08-21 00:50:29,563 INFO    MainThread:3046052 [internal.py:wandb_internal():90] W&B internal server running at pid: 3046052, started at: 2022-08-21 00:50:29.561259
2022-08-21 00:50:29,602 INFO    WriterThread:3046052 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220821_005027-vfnx7zhv/run-vfnx7zhv.wandb
2022-08-21 00:50:29,602 DEBUG   HandlerThread:3046052 [handler.py:handle_request():141] handle_request: run_start
2022-08-21 00:50:29,630 DEBUG   HandlerThread:3046052 [meta.py:__init__():35] meta init
2022-08-21 00:50:29,630 DEBUG   HandlerThread:3046052 [meta.py:__init__():49] meta init done
2022-08-21 00:50:29,630 DEBUG   HandlerThread:3046052 [meta.py:probe():209] probe
2022-08-21 00:50:29,639 DEBUG   HandlerThread:3046052 [meta.py:_setup_git():199] setup git
2022-08-21 00:50:29,762 DEBUG   HandlerThread:3046052 [meta.py:_setup_git():206] setup git done
2022-08-21 00:50:29,762 DEBUG   HandlerThread:3046052 [meta.py:_save_pip():53] save pip
2022-08-21 00:50:29,765 DEBUG   HandlerThread:3046052 [meta.py:_save_pip():67] save pip done
2022-08-21 00:50:29,767 DEBUG   HandlerThread:3046052 [meta.py:_save_conda():74] save conda
2022-08-21 00:50:46,787 DEBUG   HandlerThread:3046052 [meta.py:_save_conda():84] save conda done
2022-08-21 00:50:46,787 DEBUG   HandlerThread:3046052 [meta.py:probe():247] probe done
2022-08-21 00:51:01,385 WARNING MainThread:3046052 [internal.py:wandb_internal():153] Internal process interrupt: 1
2022-08-21 00:51:01,671 WARNING MainThread:3046052 [internal.py:wandb_internal():153] Internal process interrupt: 2
2022-08-21 00:51:01,671 ERROR   MainThread:3046052 [internal.py:wandb_internal():156] Internal process interrupted.
2022-08-21 00:51:02,505 INFO    WriterThread:3046052 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220821_005027-vfnx7zhv/run-vfnx7zhv.wandb
2022-08-21 00:51:02,671 INFO    SenderThread:3046052 [sender.py:finish():1111] shutting down sender
2022-08-21 00:51:02,672 INFO    MainThread:3046052 [internal.py:handle_exit():80] Internal process exited
