2022-12-24 07:05:04,222 INFO    MainThread:2145587 [internal.py:wandb_internal():90] W&B internal server running at pid: 2145587, started at: 2022-12-24 07:05:04.219202
2022-12-24 07:05:04,252 INFO    WriterThread:2145587 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221224_070502-23yicz4c/run-23yicz4c.wandb
2022-12-24 07:05:04,252 DEBUG   HandlerThread:2145587 [handler.py:handle_request():141] handle_request: run_start
2022-12-24 07:05:04,274 DEBUG   HandlerThread:2145587 [meta.py:__init__():35] meta init
2022-12-24 07:05:04,274 DEBUG   HandlerThread:2145587 [meta.py:__init__():49] meta init done
2022-12-24 07:05:04,274 DEBUG   HandlerThread:2145587 [meta.py:probe():209] probe
2022-12-24 07:05:04,282 DEBUG   HandlerThread:2145587 [meta.py:_setup_git():199] setup git
2022-12-24 07:05:04,409 DEBUG   HandlerThread:2145587 [meta.py:_setup_git():206] setup git done
2022-12-24 07:05:04,410 DEBUG   HandlerThread:2145587 [meta.py:_save_pip():53] save pip
2022-12-24 07:05:04,413 DEBUG   HandlerThread:2145587 [meta.py:_save_pip():67] save pip done
2022-12-24 07:05:04,414 DEBUG   HandlerThread:2145587 [meta.py:_save_conda():74] save conda
2022-12-24 07:05:13,255 WARNING MainThread:2145587 [internal.py:is_dead():387] Internal process exiting, parent pid 2145221 disappeared
2022-12-24 07:05:13,256 ERROR   MainThread:2145587 [internal.py:wandb_internal():149] Internal process shutdown.
2022-12-24 07:05:13,256 INFO    WriterThread:2145587 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221224_070502-23yicz4c/run-23yicz4c.wandb
2022-12-24 07:05:13,936 DEBUG   HandlerThread:2145587 [meta.py:_save_conda():84] save conda done
2022-12-24 07:05:13,936 DEBUG   HandlerThread:2145587 [meta.py:probe():247] probe done
2022-12-24 07:05:14,250 INFO    SenderThread:2145587 [sender.py:finish():1111] shutting down sender
2022-12-24 07:05:14,462 INFO    HandlerThread:2145587 [handler.py:finish():806] shutting down handler
2022-12-24 07:05:14,462 INFO    MainThread:2145587 [internal.py:handle_exit():80] Internal process exited
