2022-07-22 17:40:56,469 INFO    MainThread:2486787 [internal.py:wandb_internal():90] W&B internal server running at pid: 2486787, started at: 2022-07-22 17:40:56.465615
2022-07-22 17:40:56,497 INFO    WriterThread:2486787 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220722_174053-vl9e4m0e/run-vl9e4m0e.wandb
2022-07-22 17:40:56,499 DEBUG   HandlerThread:2486787 [handler.py:handle_request():141] handle_request: run_start
2022-07-22 17:40:56,541 DEBUG   HandlerThread:2486787 [meta.py:__init__():35] meta init
2022-07-22 17:40:56,542 DEBUG   HandlerThread:2486787 [meta.py:__init__():49] meta init done
2022-07-22 17:40:56,542 DEBUG   HandlerThread:2486787 [meta.py:probe():209] probe
2022-07-22 17:40:56,561 DEBUG   HandlerThread:2486787 [meta.py:_setup_git():199] setup git
2022-07-22 17:40:56,707 DEBUG   HandlerThread:2486787 [meta.py:_setup_git():206] setup git done
2022-07-22 17:40:56,707 DEBUG   HandlerThread:2486787 [meta.py:_save_pip():53] save pip
2022-07-22 17:40:56,711 DEBUG   HandlerThread:2486787 [meta.py:_save_pip():67] save pip done
2022-07-22 17:40:56,712 DEBUG   HandlerThread:2486787 [meta.py:_save_conda():74] save conda
2022-07-22 17:41:05,506 WARNING MainThread:2486787 [internal.py:is_dead():387] Internal process exiting, parent pid 2463170 disappeared
2022-07-22 17:41:05,506 ERROR   MainThread:2486787 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-22 17:41:05,507 INFO    WriterThread:2486787 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220722_174053-vl9e4m0e/run-vl9e4m0e.wandb
2022-07-22 17:41:05,507 INFO    SenderThread:2486787 [sender.py:finish():1111] shutting down sender
2022-07-22 17:41:10,293 DEBUG   HandlerThread:2486787 [meta.py:_save_conda():84] save conda done
2022-07-22 17:41:10,293 DEBUG   HandlerThread:2486787 [meta.py:probe():247] probe done
2022-07-22 17:41:10,941 INFO    HandlerThread:2486787 [handler.py:finish():806] shutting down handler
2022-07-22 17:41:10,942 INFO    MainThread:2486787 [internal.py:handle_exit():80] Internal process exited
