2022-12-14 18:58:00,663 INFO    MainThread:2821896 [internal.py:wandb_internal():90] W&B internal server running at pid: 2821896, started at: 2022-12-14 18:58:00.660271
2022-12-14 18:58:00,666 INFO    WriterThread:2821896 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221214_185758-30tzfv7d/run-30tzfv7d.wandb
2022-12-14 18:58:00,666 DEBUG   HandlerThread:2821896 [handler.py:handle_request():141] handle_request: run_start
2022-12-14 18:58:00,677 DEBUG   HandlerThread:2821896 [meta.py:__init__():35] meta init
2022-12-14 18:58:00,678 DEBUG   HandlerThread:2821896 [meta.py:__init__():49] meta init done
2022-12-14 18:58:00,678 DEBUG   HandlerThread:2821896 [meta.py:probe():209] probe
2022-12-14 18:58:00,687 DEBUG   HandlerThread:2821896 [meta.py:_setup_git():199] setup git
2022-12-14 18:58:00,764 DEBUG   HandlerThread:2821896 [meta.py:_setup_git():206] setup git done
2022-12-14 18:58:00,764 DEBUG   HandlerThread:2821896 [meta.py:_save_pip():53] save pip
2022-12-14 18:58:00,768 DEBUG   HandlerThread:2821896 [meta.py:_save_pip():67] save pip done
2022-12-14 18:58:00,769 DEBUG   HandlerThread:2821896 [meta.py:_save_conda():74] save conda
2022-12-14 18:58:18,581 DEBUG   HandlerThread:2821896 [meta.py:_save_conda():84] save conda done
2022-12-14 18:58:18,581 DEBUG   HandlerThread:2821896 [meta.py:probe():247] probe done
2022-12-14 18:58:49,714 WARNING MainThread:2821896 [internal.py:is_dead():387] Internal process exiting, parent pid 2821861 disappeared
2022-12-14 18:58:49,714 ERROR   MainThread:2821896 [internal.py:wandb_internal():149] Internal process shutdown.
2022-12-14 18:58:50,103 INFO    HandlerThread:2821896 [handler.py:finish():806] shutting down handler
2022-12-14 18:58:50,104 INFO    WriterThread:2821896 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221214_185758-30tzfv7d/run-30tzfv7d.wandb
2022-12-14 18:58:50,681 INFO    SenderThread:2821896 [sender.py:finish():1111] shutting down sender
2022-12-14 18:58:50,682 INFO    MainThread:2821896 [internal.py:handle_exit():80] Internal process exited
