2022-07-19 23:17:18,102 INFO    MainThread:3467811 [internal.py:wandb_internal():90] W&B internal server running at pid: 3467811, started at: 2022-07-19 23:17:18.100687
2022-07-19 23:17:18,126 INFO    WriterThread:3467811 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_231716-2lwbttte/run-2lwbttte.wandb
2022-07-19 23:17:18,127 DEBUG   HandlerThread:3467811 [handler.py:handle_request():141] handle_request: run_start
2022-07-19 23:17:18,155 DEBUG   HandlerThread:3467811 [meta.py:__init__():35] meta init
2022-07-19 23:17:18,155 DEBUG   HandlerThread:3467811 [meta.py:__init__():49] meta init done
2022-07-19 23:17:18,155 DEBUG   HandlerThread:3467811 [meta.py:probe():209] probe
2022-07-19 23:17:18,172 DEBUG   HandlerThread:3467811 [meta.py:_setup_git():199] setup git
2022-07-19 23:17:18,287 DEBUG   HandlerThread:3467811 [meta.py:_setup_git():206] setup git done
2022-07-19 23:17:18,287 DEBUG   HandlerThread:3467811 [meta.py:_save_pip():53] save pip
2022-07-19 23:17:18,291 DEBUG   HandlerThread:3467811 [meta.py:_save_pip():67] save pip done
2022-07-19 23:17:18,291 DEBUG   HandlerThread:3467811 [meta.py:_save_conda():74] save conda
2022-07-19 23:17:34,781 DEBUG   HandlerThread:3467811 [meta.py:_save_conda():84] save conda done
2022-07-19 23:17:34,782 DEBUG   HandlerThread:3467811 [meta.py:probe():247] probe done
2022-07-19 23:17:51,155 WARNING MainThread:3467811 [internal.py:is_dead():387] Internal process exiting, parent pid 3467670 disappeared
2022-07-19 23:17:51,155 ERROR   MainThread:3467811 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-19 23:17:51,912 INFO    HandlerThread:3467811 [handler.py:finish():806] shutting down handler
2022-07-19 23:17:51,912 INFO    WriterThread:3467811 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_231716-2lwbttte/run-2lwbttte.wandb
2022-07-19 23:17:52,149 INFO    SenderThread:3467811 [sender.py:finish():1111] shutting down sender
2022-07-19 23:17:52,151 INFO    MainThread:3467811 [internal.py:handle_exit():80] Internal process exited
