2022-07-19 23:23:33,963 INFO    MainThread:3473385 [internal.py:wandb_internal():90] W&B internal server running at pid: 3473385, started at: 2022-07-19 23:23:33.960923
2022-07-19 23:23:33,965 INFO    WriterThread:3473385 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_232331-2urb85tk/run-2urb85tk.wandb
2022-07-19 23:23:33,965 DEBUG   HandlerThread:3473385 [handler.py:handle_request():141] handle_request: run_start
2022-07-19 23:23:33,977 DEBUG   HandlerThread:3473385 [meta.py:__init__():35] meta init
2022-07-19 23:23:33,977 DEBUG   HandlerThread:3473385 [meta.py:__init__():49] meta init done
2022-07-19 23:23:33,977 DEBUG   HandlerThread:3473385 [meta.py:probe():209] probe
2022-07-19 23:23:33,985 DEBUG   HandlerThread:3473385 [meta.py:_setup_git():199] setup git
2022-07-19 23:23:34,098 DEBUG   HandlerThread:3473385 [meta.py:_setup_git():206] setup git done
2022-07-19 23:23:34,098 DEBUG   HandlerThread:3473385 [meta.py:_save_pip():53] save pip
2022-07-19 23:23:34,102 DEBUG   HandlerThread:3473385 [meta.py:_save_pip():67] save pip done
2022-07-19 23:23:34,102 DEBUG   HandlerThread:3473385 [meta.py:_save_conda():74] save conda
2022-07-19 23:23:34,966 WARNING MainThread:3473385 [internal.py:is_dead():387] Internal process exiting, parent pid 3473266 disappeared
2022-07-19 23:23:34,966 ERROR   MainThread:3473385 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-19 23:23:34,967 INFO    WriterThread:3473385 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_232331-2urb85tk/run-2urb85tk.wandb
2022-07-19 23:23:34,971 INFO    SenderThread:3473385 [sender.py:finish():1111] shutting down sender
2022-07-19 23:23:41,565 DEBUG   HandlerThread:3473385 [meta.py:_save_conda():84] save conda done
2022-07-19 23:23:41,565 DEBUG   HandlerThread:3473385 [meta.py:probe():247] probe done
2022-07-19 23:23:42,016 INFO    HandlerThread:3473385 [handler.py:finish():806] shutting down handler
2022-07-19 23:23:42,017 INFO    MainThread:3473385 [internal.py:handle_exit():80] Internal process exited
