2022-07-19 23:11:09,789 INFO    MainThread:3462838 [internal.py:wandb_internal():90] W&B internal server running at pid: 3462838, started at: 2022-07-19 23:11:09.787076
2022-07-19 23:11:09,814 INFO    WriterThread:3462838 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_231107-t2urn3rd/run-t2urn3rd.wandb
2022-07-19 23:11:09,814 DEBUG   HandlerThread:3462838 [handler.py:handle_request():141] handle_request: run_start
2022-07-19 23:11:09,851 DEBUG   HandlerThread:3462838 [meta.py:__init__():35] meta init
2022-07-19 23:11:09,852 DEBUG   HandlerThread:3462838 [meta.py:__init__():49] meta init done
2022-07-19 23:11:09,852 DEBUG   HandlerThread:3462838 [meta.py:probe():209] probe
2022-07-19 23:11:09,871 DEBUG   HandlerThread:3462838 [meta.py:_setup_git():199] setup git
2022-07-19 23:11:09,988 DEBUG   HandlerThread:3462838 [meta.py:_setup_git():206] setup git done
2022-07-19 23:11:09,988 DEBUG   HandlerThread:3462838 [meta.py:_save_pip():53] save pip
2022-07-19 23:11:09,991 DEBUG   HandlerThread:3462838 [meta.py:_save_pip():67] save pip done
2022-07-19 23:11:09,992 DEBUG   HandlerThread:3462838 [meta.py:_save_conda():74] save conda
2022-07-19 23:11:22,239 DEBUG   HandlerThread:3462838 [meta.py:_save_conda():84] save conda done
2022-07-19 23:11:22,240 DEBUG   HandlerThread:3462838 [meta.py:probe():247] probe done
2022-07-19 23:11:26,834 WARNING MainThread:3462838 [internal.py:is_dead():387] Internal process exiting, parent pid 3462721 disappeared
2022-07-19 23:11:26,835 ERROR   MainThread:3462838 [internal.py:wandb_internal():149] Internal process shutdown.
2022-07-19 23:11:26,835 INFO    SenderThread:3462838 [sender.py:finish():1111] shutting down sender
2022-07-19 23:11:27,679 INFO    WriterThread:3462838 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220719_231107-t2urn3rd/run-t2urn3rd.wandb
2022-07-19 23:11:27,683 INFO    HandlerThread:3462838 [handler.py:finish():806] shutting down handler
2022-07-19 23:11:27,683 INFO    MainThread:3462838 [internal.py:handle_exit():80] Internal process exited
