2022-12-14 20:23:56,437 INFO    MainThread:2828562 [internal.py:wandb_internal():90] W&B internal server running at pid: 2828562, started at: 2022-12-14 20:23:56.434158
2022-12-14 20:23:56,460 INFO    WriterThread:2828562 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221214_202354-22d0olcq/run-22d0olcq.wandb
2022-12-14 20:23:56,461 DEBUG   HandlerThread:2828562 [handler.py:handle_request():141] handle_request: run_start
2022-12-14 20:23:56,492 DEBUG   HandlerThread:2828562 [meta.py:__init__():35] meta init
2022-12-14 20:23:56,492 DEBUG   HandlerThread:2828562 [meta.py:__init__():49] meta init done
2022-12-14 20:23:56,492 DEBUG   HandlerThread:2828562 [meta.py:probe():209] probe
2022-12-14 20:23:56,509 DEBUG   HandlerThread:2828562 [meta.py:_setup_git():199] setup git
2022-12-14 20:23:56,629 DEBUG   HandlerThread:2828562 [meta.py:_setup_git():206] setup git done
2022-12-14 20:23:56,629 DEBUG   HandlerThread:2828562 [meta.py:_save_pip():53] save pip
2022-12-14 20:23:56,632 DEBUG   HandlerThread:2828562 [meta.py:_save_pip():67] save pip done
2022-12-14 20:23:56,633 DEBUG   HandlerThread:2828562 [meta.py:_save_conda():74] save conda
2022-12-14 20:24:13,825 DEBUG   HandlerThread:2828562 [meta.py:_save_conda():84] save conda done
2022-12-14 20:24:13,825 DEBUG   HandlerThread:2828562 [meta.py:probe():247] probe done
2022-12-14 20:24:37,493 WARNING MainThread:2828562 [internal.py:is_dead():387] Internal process exiting, parent pid 2828531 disappeared
2022-12-14 20:24:37,493 ERROR   MainThread:2828562 [internal.py:wandb_internal():149] Internal process shutdown.
2022-12-14 20:24:37,524 INFO    HandlerThread:2828562 [handler.py:finish():806] shutting down handler
2022-12-14 20:24:37,525 INFO    WriterThread:2828562 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221214_202354-22d0olcq/run-22d0olcq.wandb
2022-12-14 20:24:38,470 INFO    SenderThread:2828562 [sender.py:finish():1111] shutting down sender
2022-12-14 20:24:38,472 INFO    MainThread:2828562 [internal.py:handle_exit():80] Internal process exited
