2022-11-09 08:54:41,892 INFO    MainThread:1354616 [internal.py:wandb_internal():90] W&B internal server running at pid: 1354616, started at: 2022-11-09 08:54:41.889972
2022-11-09 08:54:41,918 INFO    WriterThread:1354616 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221109_085439-3ggrylg6/run-3ggrylg6.wandb
2022-11-09 08:54:41,919 DEBUG   HandlerThread:1354616 [handler.py:handle_request():141] handle_request: run_start
2022-11-09 08:54:41,953 DEBUG   HandlerThread:1354616 [meta.py:__init__():35] meta init
2022-11-09 08:54:41,953 DEBUG   HandlerThread:1354616 [meta.py:__init__():49] meta init done
2022-11-09 08:54:41,953 DEBUG   HandlerThread:1354616 [meta.py:probe():209] probe
2022-11-09 08:54:41,963 DEBUG   HandlerThread:1354616 [meta.py:_setup_git():199] setup git
2022-11-09 08:54:42,095 DEBUG   HandlerThread:1354616 [meta.py:_setup_git():206] setup git done
2022-11-09 08:54:42,096 DEBUG   HandlerThread:1354616 [meta.py:_save_pip():53] save pip
2022-11-09 08:54:42,099 DEBUG   HandlerThread:1354616 [meta.py:_save_pip():67] save pip done
2022-11-09 08:54:42,105 DEBUG   HandlerThread:1354616 [meta.py:_save_conda():74] save conda
2022-11-09 08:55:07,235 DEBUG   HandlerThread:1354616 [meta.py:_save_conda():84] save conda done
2022-11-09 08:55:07,236 DEBUG   HandlerThread:1354616 [meta.py:probe():247] probe done
2022-11-09 08:55:14,946 WARNING MainThread:1354616 [internal.py:is_dead():387] Internal process exiting, parent pid 1354392 disappeared
2022-11-09 08:55:14,946 ERROR   MainThread:1354616 [internal.py:wandb_internal():149] Internal process shutdown.
2022-11-09 08:55:15,202 INFO    WriterThread:1354616 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221109_085439-3ggrylg6/run-3ggrylg6.wandb
2022-11-09 08:55:15,203 INFO    HandlerThread:1354616 [handler.py:finish():806] shutting down handler
2022-11-09 08:55:15,932 INFO    SenderThread:1354616 [sender.py:finish():1111] shutting down sender
2022-11-09 08:55:15,932 INFO    MainThread:1354616 [internal.py:handle_exit():80] Internal process exited
