2022-11-15 22:29:29,644 INFO    MainThread:2676678 [internal.py:wandb_internal():90] W&B internal server running at pid: 2676678, started at: 2022-11-15 22:29:29.641034
2022-11-15 22:29:29,646 INFO    WriterThread:2676678 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221115_222927-18m49j0r/run-18m49j0r.wandb
2022-11-15 22:29:29,646 DEBUG   HandlerThread:2676678 [handler.py:handle_request():141] handle_request: run_start
2022-11-15 22:29:29,658 DEBUG   HandlerThread:2676678 [meta.py:__init__():35] meta init
2022-11-15 22:29:29,658 DEBUG   HandlerThread:2676678 [meta.py:__init__():49] meta init done
2022-11-15 22:29:29,658 DEBUG   HandlerThread:2676678 [meta.py:probe():209] probe
2022-11-15 22:29:29,668 DEBUG   HandlerThread:2676678 [meta.py:_setup_git():199] setup git
2022-11-15 22:29:29,741 DEBUG   HandlerThread:2676678 [meta.py:_setup_git():206] setup git done
2022-11-15 22:29:29,741 DEBUG   HandlerThread:2676678 [meta.py:_save_pip():53] save pip
2022-11-15 22:29:29,745 DEBUG   HandlerThread:2676678 [meta.py:_save_pip():67] save pip done
2022-11-15 22:29:29,746 DEBUG   HandlerThread:2676678 [meta.py:_save_conda():74] save conda
2022-11-15 22:29:48,144 DEBUG   HandlerThread:2676678 [meta.py:_save_conda():84] save conda done
2022-11-15 22:29:48,144 DEBUG   HandlerThread:2676678 [meta.py:probe():247] probe done
2022-11-15 22:29:54,669 WARNING MainThread:2676678 [internal.py:is_dead():387] Internal process exiting, parent pid 2676481 disappeared
2022-11-15 22:29:54,669 ERROR   MainThread:2676678 [internal.py:wandb_internal():149] Internal process shutdown.
2022-11-15 22:29:54,733 INFO    HandlerThread:2676678 [handler.py:finish():806] shutting down handler
2022-11-15 22:29:54,734 INFO    WriterThread:2676678 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20221115_222927-18m49j0r/run-18m49j0r.wandb
2022-11-15 22:29:55,660 INFO    SenderThread:2676678 [sender.py:finish():1111] shutting down sender
2022-11-15 22:29:55,661 INFO    MainThread:2676678 [internal.py:handle_exit():80] Internal process exited
